# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion

# Install wget with IRI support
install wget --enable-iri

# Install RingoJS and Narwhal
# Note that the order in which these are installed is important; see http://git.io/brew-narwhal-ringo.
install ringojs
install narwhal

# Install more recent versions of some OS X tools
install vim --override-system-vi
install homebrew/dupes/grep
install homebrew/php/php55 --with-gmp
install emacs
install python --framework

# This formula didn’t work well last time I tried it:
#install homebrew/dupes/screen

# Datastores
install elasticsearch
install mysql
install redis
install memcache
install couchdb

# Install other useful binaries
install ack
install android-sdk
install ant
install cairo
install chromaprint
install closure-compiler
install echoprint-codegen
#install exiv2
install ffmpeg
install foremost
install git
install hashpump
install imagemagick --with-webp
install lastfmfpclient
install libxml2
install libxslt
install homebrew/versions/libpng12
install lynx
install nmap
install node # This installs `npm` too using the recommended installation method
install p7zip
install pigz
install pv
install py2cairo
install rename
install rhino
install sox
install sqlmap
install taglib
install tree
install ucspi-tcp # `tcpserver` et al.
install webkit2png
install xpdf
install zlib
install zopfli

install homebrew/versions/lua52

# Remove outdated versions from the cellar
cleanup
